//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEDESOL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATTENDANCE
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public string Curp { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> Id_Capture { get; set; }
        public Nullable<int> Id_Receiver { get; set; }
        public bool IsActive { get; set; }
        public bool IsAnonym { get; set; }
        public string Gender { get; set; }
        public Nullable<int> Id_Condition { get; set; }
        public Nullable<int> Id_State_Birth { get; set; }
        public string Address { get; set; }
        public string PhoneNumber { get; set; }
        public string LastName2 { get; set; }
    
        public virtual CAPTURE CAPTURE { get; set; }
        public virtual RECEIVER RECEIVER { get; set; }
        public virtual CONDITION CONDITION { get; set; }
        public virtual STATE STATE { get; set; }
    }
}
