//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEDESOL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAPTURE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAPTURE()
        {
            this.ATTENDANCEs = new HashSet<ATTENDANCE>();
            this.CAPTURE_HISTORY = new HashSet<CAPTURE_HISTORY>();
            this.CAPTURE_IMAGE = new HashSet<CAPTURE_IMAGE>();
            this.CAPTURE_APPROVAL = new HashSet<CAPTURE_APPROVAL>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool IsActive { get; set; }
        public int Id_Month { get; set; }
        public int Id_Year { get; set; }
        public int Id_Status { get; set; }
        public int Id_SoupKitchen { get; set; }
        public string Folio { get; set; }
        public string InspectionCode { get; set; }
        public int Id_LevelApproval { get; set; }
        public int Id_User { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATTENDANCE> ATTENDANCEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAPTURE_HISTORY> CAPTURE_HISTORY { get; set; }
        public virtual MONTH MONTH { get; set; }
        public virtual SOUP_KITCHEN SOUP_KITCHEN { get; set; }
        public virtual STATUS STATUS { get; set; }
        public virtual YEAR YEAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAPTURE_IMAGE> CAPTURE_IMAGE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAPTURE_APPROVAL> CAPTURE_APPROVAL { get; set; }
        public virtual USER_TYPE USER_TYPE { get; set; }
        public virtual USER USER { get; set; }
    }
}
