//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEDESOL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAPTURE_APPROVAL
    {
        public int Id { get; set; }
        public int Id_Capture { get; set; }
        public int Id_User { get; set; }
        public int Id_Status { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual CAPTURE CAPTURE { get; set; }
        public virtual STATUS STATUS { get; set; }
        public virtual USER USER { get; set; }
    }
}
