//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEDESOL.DataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RATION
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public int Id_SoupKitchen { get; set; }
        public int Id_Month { get; set; }
        public int Id_Year { get; set; }
        public Nullable<int> Id_Capture { get; set; }
        public decimal RationQuantity { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string EditUser { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public Nullable<bool> HasCoupon { get; set; }
    
        public virtual MONTH MONTH { get; set; }
        public virtual SOUP_KITCHEN SOUP_KITCHEN { get; set; }
        public virtual YEAR YEAR { get; set; }
    }
}
