//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEDESOL.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using SEDESOL.DataEntities;
    
    public partial class SEDESOLEntities : DbContext
    {
        public SEDESOLEntities()
            : base("name=SEDESOLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ATTENDANCE> ATTENDANCEs { get; set; }
        public virtual DbSet<CAPTURE> CAPTUREs { get; set; }
        public virtual DbSet<CAPTURE_HISTORY> CAPTURE_HISTORY { get; set; }
        public virtual DbSet<MONTH> MONTHs { get; set; }
        public virtual DbSet<RECEIVER> RECEIVERs { get; set; }
        public virtual DbSet<SOUP_KITCHEN> SOUP_KITCHEN { get; set; }
        public virtual DbSet<STATE> STATEs { get; set; }
        public virtual DbSet<STATUS> STATUS { get; set; }
        public virtual DbSet<USER> USERs { get; set; }
        public virtual DbSet<USER_SOUP_KITCHEN> USER_SOUP_KITCHEN { get; set; }
        public virtual DbSet<USER_TYPE> USER_TYPE { get; set; }
        public virtual DbSet<YEAR> YEARs { get; set; }
        public virtual DbSet<CAPTURE_IMAGE> CAPTURE_IMAGE { get; set; }
        public virtual DbSet<SOUP_KITCHEN_USER_TYPE> SOUP_KITCHEN_USER_TYPE { get; set; }
        public virtual DbSet<GEN_CODE_DAY> GEN_CODE_DAY { get; set; }
        public virtual DbSet<INSPECTION_CODE> INSPECTION_CODE { get; set; }
        public virtual DbSet<CAPTURE_APPROVAL> CAPTURE_APPROVAL { get; set; }
        public virtual DbSet<CONDITION> CONDITIONs { get; set; }
        public virtual DbSet<COUPON> COUPONs { get; set; }
        public virtual DbSet<COUPON_DETAIL> COUPON_DETAIL { get; set; }
        public virtual DbSet<PRODUCT> PRODUCTs { get; set; }
        public virtual DbSet<RATION> RATIONs { get; set; }
        public virtual DbSet<REGION> REGIONs { get; set; }
        public virtual DbSet<REGION_PRODUCT> REGION_PRODUCT { get; set; }
        public virtual DbSet<CONFIGURATION> CONFIGURATIONs { get; set; }
    }
}
