//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEDESOL.UI.SedesolService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SedesolService.ISedesolService")]
    public interface ISedesolService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/GetCaptures", ReplyAction="http://tempuri.org/ISedesolService/GetCapturesResponse")]
        System.Collections.Generic.List<SEDESOL.DataEntities.DTO.CaptureDTO> GetCaptures();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/GetCaptures", ReplyAction="http://tempuri.org/ISedesolService/GetCapturesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SEDESOL.DataEntities.DTO.CaptureDTO>> GetCapturesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/GetCapturesSearch", ReplyAction="http://tempuri.org/ISedesolService/GetCapturesSearchResponse")]
        System.Collections.Generic.List<SEDESOL.DataEntities.DTO.CaptureDTO> GetCapturesSearch(int userTypeId, int userId, int pState, int pSoupK, int pStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/GetCapturesSearch", ReplyAction="http://tempuri.org/ISedesolService/GetCapturesSearchResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SEDESOL.DataEntities.DTO.CaptureDTO>> GetCapturesSearchAsync(int userTypeId, int userId, int pState, int pSoupK, int pStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/GetCapturesFilter", ReplyAction="http://tempuri.org/ISedesolService/GetCapturesFilterResponse")]
        System.Collections.Generic.List<SEDESOL.DataEntities.DTO.CaptureDTO> GetCapturesFilter(int userTypeId, int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/GetCapturesFilter", ReplyAction="http://tempuri.org/ISedesolService/GetCapturesFilterResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SEDESOL.DataEntities.DTO.CaptureDTO>> GetCapturesFilterAsync(int userTypeId, int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/ActivateCapture", ReplyAction="http://tempuri.org/ISedesolService/ActivateCaptureResponse")]
        void ActivateCapture(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/ActivateCapture", ReplyAction="http://tempuri.org/ISedesolService/ActivateCaptureResponse")]
        System.Threading.Tasks.Task ActivateCaptureAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/DeactivateCapture", ReplyAction="http://tempuri.org/ISedesolService/DeactivateCaptureResponse")]
        void DeactivateCapture(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/DeactivateCapture", ReplyAction="http://tempuri.org/ISedesolService/DeactivateCaptureResponse")]
        System.Threading.Tasks.Task DeactivateCaptureAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/SaveCapture", ReplyAction="http://tempuri.org/ISedesolService/SaveCaptureResponse")]
        SEDESOL.DataEntities.DTO.CaptureDTO SaveCapture(SEDESOL.DataEntities.DTO.CaptureDTO capture);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/SaveCapture", ReplyAction="http://tempuri.org/ISedesolService/SaveCaptureResponse")]
        System.Threading.Tasks.Task<SEDESOL.DataEntities.DTO.CaptureDTO> SaveCaptureAsync(SEDESOL.DataEntities.DTO.CaptureDTO capture);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/UpdateCapture", ReplyAction="http://tempuri.org/ISedesolService/UpdateCaptureResponse")]
        bool UpdateCapture(SEDESOL.DataEntities.DTO.CaptureDTO capture);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/UpdateCapture", ReplyAction="http://tempuri.org/ISedesolService/UpdateCaptureResponse")]
        System.Threading.Tasks.Task<bool> UpdateCaptureAsync(SEDESOL.DataEntities.DTO.CaptureDTO capture);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/GetCaptureById", ReplyAction="http://tempuri.org/ISedesolService/GetCaptureByIdResponse")]
        SEDESOL.DataEntities.DTO.CaptureDTO GetCaptureById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/GetCaptureById", ReplyAction="http://tempuri.org/ISedesolService/GetCaptureByIdResponse")]
        System.Threading.Tasks.Task<SEDESOL.DataEntities.DTO.CaptureDTO> GetCaptureByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/SaveCaptureImage", ReplyAction="http://tempuri.org/ISedesolService/SaveCaptureImageResponse")]
        int SaveCaptureImage(SEDESOL.DataEntities.DTO.CaptureImageDTO dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/SaveCaptureImage", ReplyAction="http://tempuri.org/ISedesolService/SaveCaptureImageResponse")]
        System.Threading.Tasks.Task<int> SaveCaptureImageAsync(SEDESOL.DataEntities.DTO.CaptureImageDTO dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/DeleteCaptureImage", ReplyAction="http://tempuri.org/ISedesolService/DeleteCaptureImageResponse")]
        string DeleteCaptureImage(int FileId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/DeleteCaptureImage", ReplyAction="http://tempuri.org/ISedesolService/DeleteCaptureImageResponse")]
        System.Threading.Tasks.Task<string> DeleteCaptureImageAsync(int FileId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/GetImageByCaptureId", ReplyAction="http://tempuri.org/ISedesolService/GetImageByCaptureIdResponse")]
        System.Collections.Generic.List<SEDESOL.DataEntities.DTO.CaptureImageDTO> GetImageByCaptureId(int pCaptureId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/GetImageByCaptureId", ReplyAction="http://tempuri.org/ISedesolService/GetImageByCaptureIdResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SEDESOL.DataEntities.DTO.CaptureImageDTO>> GetImageByCaptureIdAsync(int pCaptureId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/GetCodesByUserId", ReplyAction="http://tempuri.org/ISedesolService/GetCodesByUserIdResponse")]
        System.Collections.Generic.List<SEDESOL.DataEntities.DTO.InspectionCodeDTO> GetCodesByUserId(int pUserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/GetCodesByUserId", ReplyAction="http://tempuri.org/ISedesolService/GetCodesByUserIdResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SEDESOL.DataEntities.DTO.InspectionCodeDTO>> GetCodesByUserIdAsync(int pUserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/SendToApproval", ReplyAction="http://tempuri.org/ISedesolService/SendToApprovalResponse")]
        string SendToApproval(SEDESOL.DataEntities.DTO.CaptureApprovalDTO dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/SendToApproval", ReplyAction="http://tempuri.org/ISedesolService/SendToApprovalResponse")]
        System.Threading.Tasks.Task<string> SendToApprovalAsync(SEDESOL.DataEntities.DTO.CaptureApprovalDTO dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/GetParamCapture", ReplyAction="http://tempuri.org/ISedesolService/GetParamCaptureResponse")]
        SEDESOL.DataEntities.IntegrationObjects.CaptureParam GetParamCapture(int userTypeId, int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/GetParamCapture", ReplyAction="http://tempuri.org/ISedesolService/GetParamCaptureResponse")]
        System.Threading.Tasks.Task<SEDESOL.DataEntities.IntegrationObjects.CaptureParam> GetParamCaptureAsync(int userTypeId, int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/EditStatus", ReplyAction="http://tempuri.org/ISedesolService/EditStatusResponse")]
        string EditStatus(int idStatus, int idCapture, int idUserType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/EditStatus", ReplyAction="http://tempuri.org/ISedesolService/EditStatusResponse")]
        System.Threading.Tasks.Task<string> EditStatusAsync(int idStatus, int idCapture, int idUserType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/GetStates", ReplyAction="http://tempuri.org/ISedesolService/GetStatesResponse")]
        System.Collections.Generic.List<SEDESOL.DataEntities.DTO.StateDTO> GetStates();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/GetStates", ReplyAction="http://tempuri.org/ISedesolService/GetStatesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SEDESOL.DataEntities.DTO.StateDTO>> GetStatesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/GetStatesFilter", ReplyAction="http://tempuri.org/ISedesolService/GetStatesFilterResponse")]
        System.Collections.Generic.List<SEDESOL.DataEntities.DTO.StateDTO> GetStatesFilter(int userTypeId, int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/GetStatesFilter", ReplyAction="http://tempuri.org/ISedesolService/GetStatesFilterResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SEDESOL.DataEntities.DTO.StateDTO>> GetStatesFilterAsync(int userTypeId, int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/GetStatus", ReplyAction="http://tempuri.org/ISedesolService/GetStatusResponse")]
        System.Collections.Generic.List<SEDESOL.DataEntities.DTO.StatusDTO> GetStatus();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/GetStatus", ReplyAction="http://tempuri.org/ISedesolService/GetStatusResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SEDESOL.DataEntities.DTO.StatusDTO>> GetStatusAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/GetYears", ReplyAction="http://tempuri.org/ISedesolService/GetYearsResponse")]
        System.Collections.Generic.List<SEDESOL.DataEntities.DTO.YearDTO> GetYears();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/GetYears", ReplyAction="http://tempuri.org/ISedesolService/GetYearsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SEDESOL.DataEntities.DTO.YearDTO>> GetYearsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/GetMonths", ReplyAction="http://tempuri.org/ISedesolService/GetMonthsResponse")]
        System.Collections.Generic.List<SEDESOL.DataEntities.DTO.MonthDTO> GetMonths();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/GetMonths", ReplyAction="http://tempuri.org/ISedesolService/GetMonthsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SEDESOL.DataEntities.DTO.MonthDTO>> GetMonthsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/UpdateState", ReplyAction="http://tempuri.org/ISedesolService/UpdateStateResponse")]
        void UpdateState(SEDESOL.DataEntities.DTO.StateDTO dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/UpdateState", ReplyAction="http://tempuri.org/ISedesolService/UpdateStateResponse")]
        System.Threading.Tasks.Task UpdateStateAsync(SEDESOL.DataEntities.DTO.StateDTO dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/UpdateStatus", ReplyAction="http://tempuri.org/ISedesolService/UpdateStatusResponse")]
        void UpdateStatus(SEDESOL.DataEntities.DTO.StatusDTO dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/UpdateStatus", ReplyAction="http://tempuri.org/ISedesolService/UpdateStatusResponse")]
        System.Threading.Tasks.Task UpdateStatusAsync(SEDESOL.DataEntities.DTO.StatusDTO dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/UpdateYear", ReplyAction="http://tempuri.org/ISedesolService/UpdateYearResponse")]
        void UpdateYear(SEDESOL.DataEntities.DTO.YearDTO dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/UpdateYear", ReplyAction="http://tempuri.org/ISedesolService/UpdateYearResponse")]
        System.Threading.Tasks.Task UpdateYearAsync(SEDESOL.DataEntities.DTO.YearDTO dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/UpdateMonth", ReplyAction="http://tempuri.org/ISedesolService/UpdateMonthResponse")]
        void UpdateMonth(SEDESOL.DataEntities.DTO.MonthDTO dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/UpdateMonth", ReplyAction="http://tempuri.org/ISedesolService/UpdateMonthResponse")]
        System.Threading.Tasks.Task UpdateMonthAsync(SEDESOL.DataEntities.DTO.MonthDTO dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/ActivateStatus", ReplyAction="http://tempuri.org/ISedesolService/ActivateStatusResponse")]
        void ActivateStatus(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/ActivateStatus", ReplyAction="http://tempuri.org/ISedesolService/ActivateStatusResponse")]
        System.Threading.Tasks.Task ActivateStatusAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/DeactivateStatus", ReplyAction="http://tempuri.org/ISedesolService/DeactivateStatusResponse")]
        void DeactivateStatus(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/DeactivateStatus", ReplyAction="http://tempuri.org/ISedesolService/DeactivateStatusResponse")]
        System.Threading.Tasks.Task DeactivateStatusAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/ActivateState", ReplyAction="http://tempuri.org/ISedesolService/ActivateStateResponse")]
        void ActivateState(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/ActivateState", ReplyAction="http://tempuri.org/ISedesolService/ActivateStateResponse")]
        System.Threading.Tasks.Task ActivateStateAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/DeactivateState", ReplyAction="http://tempuri.org/ISedesolService/DeactivateStateResponse")]
        void DeactivateState(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/DeactivateState", ReplyAction="http://tempuri.org/ISedesolService/DeactivateStateResponse")]
        System.Threading.Tasks.Task DeactivateStateAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/ActivateYear", ReplyAction="http://tempuri.org/ISedesolService/ActivateYearResponse")]
        void ActivateYear(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/ActivateYear", ReplyAction="http://tempuri.org/ISedesolService/ActivateYearResponse")]
        System.Threading.Tasks.Task ActivateYearAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/DeactivateYear", ReplyAction="http://tempuri.org/ISedesolService/DeactivateYearResponse")]
        void DeactivateYear(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/DeactivateYear", ReplyAction="http://tempuri.org/ISedesolService/DeactivateYearResponse")]
        System.Threading.Tasks.Task DeactivateYearAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/ActivateMonth", ReplyAction="http://tempuri.org/ISedesolService/ActivateMonthResponse")]
        void ActivateMonth(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/ActivateMonth", ReplyAction="http://tempuri.org/ISedesolService/ActivateMonthResponse")]
        System.Threading.Tasks.Task ActivateMonthAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/DeactivateMonth", ReplyAction="http://tempuri.org/ISedesolService/DeactivateMonthResponse")]
        void DeactivateMonth(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/DeactivateMonth", ReplyAction="http://tempuri.org/ISedesolService/DeactivateMonthResponse")]
        System.Threading.Tasks.Task DeactivateMonthAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/GetParamCode", ReplyAction="http://tempuri.org/ISedesolService/GetParamCodeResponse")]
        SEDESOL.DataEntities.IntegrationObjects.CodeParam GetParamCode(int pUserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/GetParamCode", ReplyAction="http://tempuri.org/ISedesolService/GetParamCodeResponse")]
        System.Threading.Tasks.Task<SEDESOL.DataEntities.IntegrationObjects.CodeParam> GetParamCodeAsync(int pUserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/GenerateCode", ReplyAction="http://tempuri.org/ISedesolService/GenerateCodeResponse")]
        string GenerateCode(int pUserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/GenerateCode", ReplyAction="http://tempuri.org/ISedesolService/GenerateCodeResponse")]
        System.Threading.Tasks.Task<string> GenerateCodeAsync(int pUserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/GetActiveStates", ReplyAction="http://tempuri.org/ISedesolService/GetActiveStatesResponse")]
        System.Collections.Generic.List<SEDESOL.DataEntities.DTO.StateDTO> GetActiveStates();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/GetActiveStates", ReplyAction="http://tempuri.org/ISedesolService/GetActiveStatesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SEDESOL.DataEntities.DTO.StateDTO>> GetActiveStatesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/GetActiveCondition", ReplyAction="http://tempuri.org/ISedesolService/GetActiveConditionResponse")]
        System.Collections.Generic.List<SEDESOL.DataEntities.DTO.ConditionDTO> GetActiveCondition();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/GetActiveCondition", ReplyAction="http://tempuri.org/ISedesolService/GetActiveConditionResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SEDESOL.DataEntities.DTO.ConditionDTO>> GetActiveConditionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/GetActiveRegions", ReplyAction="http://tempuri.org/ISedesolService/GetActiveRegionsResponse")]
        System.Collections.Generic.List<SEDESOL.DataEntities.DTO.RegionDTO> GetActiveRegions();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/GetActiveRegions", ReplyAction="http://tempuri.org/ISedesolService/GetActiveRegionsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SEDESOL.DataEntities.DTO.RegionDTO>> GetActiveRegionsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/SaveAttendance", ReplyAction="http://tempuri.org/ISedesolService/SaveAttendanceResponse")]
        SEDESOL.DataEntities.DTO.AttendanceDTO SaveAttendance(SEDESOL.DataEntities.DTO.AttendanceDTO dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/SaveAttendance", ReplyAction="http://tempuri.org/ISedesolService/SaveAttendanceResponse")]
        System.Threading.Tasks.Task<SEDESOL.DataEntities.DTO.AttendanceDTO> SaveAttendanceAsync(SEDESOL.DataEntities.DTO.AttendanceDTO dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/GetAttendanceById", ReplyAction="http://tempuri.org/ISedesolService/GetAttendanceByIdResponse")]
        SEDESOL.DataEntities.DTO.AttendanceDTO GetAttendanceById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/GetAttendanceById", ReplyAction="http://tempuri.org/ISedesolService/GetAttendanceByIdResponse")]
        System.Threading.Tasks.Task<SEDESOL.DataEntities.DTO.AttendanceDTO> GetAttendanceByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/DeleteAttendance", ReplyAction="http://tempuri.org/ISedesolService/DeleteAttendanceResponse")]
        string DeleteAttendance(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/DeleteAttendance", ReplyAction="http://tempuri.org/ISedesolService/DeleteAttendanceResponse")]
        System.Threading.Tasks.Task<string> DeleteAttendanceAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/GetDataForAc", ReplyAction="http://tempuri.org/ISedesolService/GetDataForAcResponse")]
        System.Collections.Generic.List<SEDESOL.DataEntities.DTO.AttendanceDTO> GetDataForAc(string term);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/GetDataForAc", ReplyAction="http://tempuri.org/ISedesolService/GetDataForAcResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SEDESOL.DataEntities.DTO.AttendanceDTO>> GetDataForAcAsync(string term);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/GetAttendanceReport", ReplyAction="http://tempuri.org/ISedesolService/GetAttendanceReportResponse")]
        string GetAttendanceReport(int pCaptureId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/GetAttendanceReport", ReplyAction="http://tempuri.org/ISedesolService/GetAttendanceReportResponse")]
        System.Threading.Tasks.Task<string> GetAttendanceReportAsync(int pCaptureId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/GetCaptureReport", ReplyAction="http://tempuri.org/ISedesolService/GetCaptureReportResponse")]
        string GetCaptureReport(System.Collections.Generic.List<SEDESOL.DataEntities.DTO.FilterDTO> filters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/GetCaptureReport", ReplyAction="http://tempuri.org/ISedesolService/GetCaptureReportResponse")]
        System.Threading.Tasks.Task<string> GetCaptureReportAsync(System.Collections.Generic.List<SEDESOL.DataEntities.DTO.FilterDTO> filters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/GetSoupKitchenByUser", ReplyAction="http://tempuri.org/ISedesolService/GetSoupKitchenByUserResponse")]
        System.Collections.Generic.List<SEDESOL.DataEntities.DTO.SoupKitchenDTO> GetSoupKitchenByUser(int userTypeId, int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/GetSoupKitchenByUser", ReplyAction="http://tempuri.org/ISedesolService/GetSoupKitchenByUserResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SEDESOL.DataEntities.DTO.SoupKitchenDTO>> GetSoupKitchenByUserAsync(int userTypeId, int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/ValidateUser", ReplyAction="http://tempuri.org/ISedesolService/ValidateUserResponse")]
        SEDESOL.DataEntities.DTO.UserDTO ValidateUser(SEDESOL.DataEntities.IntegrationObjects.UserValidationRequest req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/ValidateUser", ReplyAction="http://tempuri.org/ISedesolService/ValidateUserResponse")]
        System.Threading.Tasks.Task<SEDESOL.DataEntities.DTO.UserDTO> ValidateUserAsync(SEDESOL.DataEntities.IntegrationObjects.UserValidationRequest req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/SaveSoupKitchen", ReplyAction="http://tempuri.org/ISedesolService/SaveSoupKitchenResponse")]
        SEDESOL.DataEntities.DTO.SoupKitchenDTO SaveSoupKitchen(SEDESOL.DataEntities.DTO.SoupKitchenDTO dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/SaveSoupKitchen", ReplyAction="http://tempuri.org/ISedesolService/SaveSoupKitchenResponse")]
        System.Threading.Tasks.Task<SEDESOL.DataEntities.DTO.SoupKitchenDTO> SaveSoupKitchenAsync(SEDESOL.DataEntities.DTO.SoupKitchenDTO dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/GetSoupKitchenAll", ReplyAction="http://tempuri.org/ISedesolService/GetSoupKitchenAllResponse")]
        System.Collections.Generic.List<SEDESOL.DataEntities.DTO.SoupKitchenDTO> GetSoupKitchenAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/GetSoupKitchenAll", ReplyAction="http://tempuri.org/ISedesolService/GetSoupKitchenAllResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SEDESOL.DataEntities.DTO.SoupKitchenDTO>> GetSoupKitchenAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/GetSoupKitchenToAssignUser", ReplyAction="http://tempuri.org/ISedesolService/GetSoupKitchenToAssignUserResponse")]
        System.Collections.Generic.List<SEDESOL.DataEntities.DTO.SoupKitchenDTO> GetSoupKitchenToAssignUser(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/GetSoupKitchenToAssignUser", ReplyAction="http://tempuri.org/ISedesolService/GetSoupKitchenToAssignUserResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SEDESOL.DataEntities.DTO.SoupKitchenDTO>> GetSoupKitchenToAssignUserAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/GetSKAssignedUser", ReplyAction="http://tempuri.org/ISedesolService/GetSKAssignedUserResponse")]
        System.Collections.Generic.List<SEDESOL.DataEntities.DTO.SoupKitchenDTO> GetSKAssignedUser(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/GetSKAssignedUser", ReplyAction="http://tempuri.org/ISedesolService/GetSKAssignedUserResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SEDESOL.DataEntities.DTO.SoupKitchenDTO>> GetSKAssignedUserAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/GetSoupKitchenById", ReplyAction="http://tempuri.org/ISedesolService/GetSoupKitchenByIdResponse")]
        SEDESOL.DataEntities.DTO.SoupKitchenDTO GetSoupKitchenById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/GetSoupKitchenById", ReplyAction="http://tempuri.org/ISedesolService/GetSoupKitchenByIdResponse")]
        System.Threading.Tasks.Task<SEDESOL.DataEntities.DTO.SoupKitchenDTO> GetSoupKitchenByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/Deactivate", ReplyAction="http://tempuri.org/ISedesolService/DeactivateResponse")]
        void Deactivate(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/Deactivate", ReplyAction="http://tempuri.org/ISedesolService/DeactivateResponse")]
        System.Threading.Tasks.Task DeactivateAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/Activate", ReplyAction="http://tempuri.org/ISedesolService/ActivateResponse")]
        void Activate(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/Activate", ReplyAction="http://tempuri.org/ISedesolService/ActivateResponse")]
        System.Threading.Tasks.Task ActivateAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/GetUserTypeBySKId", ReplyAction="http://tempuri.org/ISedesolService/GetUserTypeBySKIdResponse")]
        System.Collections.Generic.List<SEDESOL.DataEntities.DTO.SkUserTypeDTOcs> GetUserTypeBySKId(int skId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/GetUserTypeBySKId", ReplyAction="http://tempuri.org/ISedesolService/GetUserTypeBySKIdResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SEDESOL.DataEntities.DTO.SkUserTypeDTOcs>> GetUserTypeBySKIdAsync(int skId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/DeleteUserTypeSk", ReplyAction="http://tempuri.org/ISedesolService/DeleteUserTypeSkResponse")]
        string DeleteUserTypeSk(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/DeleteUserTypeSk", ReplyAction="http://tempuri.org/ISedesolService/DeleteUserTypeSkResponse")]
        System.Threading.Tasks.Task<string> DeleteUserTypeSkAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/SaveUser", ReplyAction="http://tempuri.org/ISedesolService/SaveUserResponse")]
        SEDESOL.DataEntities.DTO.UserDTO SaveUser(SEDESOL.DataEntities.DTO.UserDTO dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/SaveUser", ReplyAction="http://tempuri.org/ISedesolService/SaveUserResponse")]
        System.Threading.Tasks.Task<SEDESOL.DataEntities.DTO.UserDTO> SaveUserAsync(SEDESOL.DataEntities.DTO.UserDTO dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/GetUserAll", ReplyAction="http://tempuri.org/ISedesolService/GetUserAllResponse")]
        System.Collections.Generic.List<SEDESOL.DataEntities.DTO.UserDTO> GetUserAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/GetUserAll", ReplyAction="http://tempuri.org/ISedesolService/GetUserAllResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SEDESOL.DataEntities.DTO.UserDTO>> GetUserAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/GetUserById", ReplyAction="http://tempuri.org/ISedesolService/GetUserByIdResponse")]
        SEDESOL.DataEntities.DTO.UserDTO GetUserById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/GetUserById", ReplyAction="http://tempuri.org/ISedesolService/GetUserByIdResponse")]
        System.Threading.Tasks.Task<SEDESOL.DataEntities.DTO.UserDTO> GetUserByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/DeactivateUser", ReplyAction="http://tempuri.org/ISedesolService/DeactivateUserResponse")]
        void DeactivateUser(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/DeactivateUser", ReplyAction="http://tempuri.org/ISedesolService/DeactivateUserResponse")]
        System.Threading.Tasks.Task DeactivateUserAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/ActivateUser", ReplyAction="http://tempuri.org/ISedesolService/ActivateUserResponse")]
        void ActivateUser(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/ActivateUser", ReplyAction="http://tempuri.org/ISedesolService/ActivateUserResponse")]
        System.Threading.Tasks.Task ActivateUserAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/GetUserTypeAll", ReplyAction="http://tempuri.org/ISedesolService/GetUserTypeAllResponse")]
        System.Collections.Generic.List<SEDESOL.DataEntities.DTO.UserTypeDTO> GetUserTypeAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/GetUserTypeAll", ReplyAction="http://tempuri.org/ISedesolService/GetUserTypeAllResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SEDESOL.DataEntities.DTO.UserTypeDTO>> GetUserTypeAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/GetUserTypeApproval", ReplyAction="http://tempuri.org/ISedesolService/GetUserTypeApprovalResponse")]
        System.Collections.Generic.List<SEDESOL.DataEntities.DTO.UserTypeDTO> GetUserTypeApproval();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/GetUserTypeApproval", ReplyAction="http://tempuri.org/ISedesolService/GetUserTypeApprovalResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SEDESOL.DataEntities.DTO.UserTypeDTO>> GetUserTypeApprovalAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/SaveUserTypeSK", ReplyAction="http://tempuri.org/ISedesolService/SaveUserTypeSKResponse")]
        SEDESOL.DataEntities.DTO.SkUserTypeDTOcs SaveUserTypeSK(SEDESOL.DataEntities.DTO.SkUserTypeDTOcs dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/SaveUserTypeSK", ReplyAction="http://tempuri.org/ISedesolService/SaveUserTypeSKResponse")]
        System.Threading.Tasks.Task<SEDESOL.DataEntities.DTO.SkUserTypeDTOcs> SaveUserTypeSKAsync(SEDESOL.DataEntities.DTO.SkUserTypeDTOcs dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/SaveUserSoupKitchen", ReplyAction="http://tempuri.org/ISedesolService/SaveUserSoupKitchenResponse")]
        SEDESOL.DataEntities.DTO.UserSoupKitchen SaveUserSoupKitchen(SEDESOL.DataEntities.DTO.UserSoupKitchen dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/SaveUserSoupKitchen", ReplyAction="http://tempuri.org/ISedesolService/SaveUserSoupKitchenResponse")]
        System.Threading.Tasks.Task<SEDESOL.DataEntities.DTO.UserSoupKitchen> SaveUserSoupKitchenAsync(SEDESOL.DataEntities.DTO.UserSoupKitchen dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/DeleteUserSoupKitchen", ReplyAction="http://tempuri.org/ISedesolService/DeleteUserSoupKitchenResponse")]
        string DeleteUserSoupKitchen(int idSk, int idUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/DeleteUserSoupKitchen", ReplyAction="http://tempuri.org/ISedesolService/DeleteUserSoupKitchenResponse")]
        System.Threading.Tasks.Task<string> DeleteUserSoupKitchenAsync(int idSk, int idUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/SaveInspectionCode", ReplyAction="http://tempuri.org/ISedesolService/SaveInspectionCodeResponse")]
        SEDESOL.DataEntities.DTO.InspectionCodeDTO SaveInspectionCode(SEDESOL.DataEntities.DTO.InspectionCodeDTO dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/SaveInspectionCode", ReplyAction="http://tempuri.org/ISedesolService/SaveInspectionCodeResponse")]
        System.Threading.Tasks.Task<SEDESOL.DataEntities.DTO.InspectionCodeDTO> SaveInspectionCodeAsync(SEDESOL.DataEntities.DTO.InspectionCodeDTO dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/GetGenerationCodeDayAll", ReplyAction="http://tempuri.org/ISedesolService/GetGenerationCodeDayAllResponse")]
        System.Collections.Generic.List<SEDESOL.DataEntities.DTO.GencodeDayDTO> GetGenerationCodeDayAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/GetGenerationCodeDayAll", ReplyAction="http://tempuri.org/ISedesolService/GetGenerationCodeDayAllResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SEDESOL.DataEntities.DTO.GencodeDayDTO>> GetGenerationCodeDayAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/SaveGencodeDay", ReplyAction="http://tempuri.org/ISedesolService/SaveGencodeDayResponse")]
        SEDESOL.DataEntities.DTO.GencodeDayDTO SaveGencodeDay(SEDESOL.DataEntities.DTO.GencodeDayDTO dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/SaveGencodeDay", ReplyAction="http://tempuri.org/ISedesolService/SaveGencodeDayResponse")]
        System.Threading.Tasks.Task<SEDESOL.DataEntities.DTO.GencodeDayDTO> SaveGencodeDayAsync(SEDESOL.DataEntities.DTO.GencodeDayDTO dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/GetGenerationCodeDayById", ReplyAction="http://tempuri.org/ISedesolService/GetGenerationCodeDayByIdResponse")]
        SEDESOL.DataEntities.DTO.GencodeDayDTO GetGenerationCodeDayById(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/GetGenerationCodeDayById", ReplyAction="http://tempuri.org/ISedesolService/GetGenerationCodeDayByIdResponse")]
        System.Threading.Tasks.Task<SEDESOL.DataEntities.DTO.GencodeDayDTO> GetGenerationCodeDayByIdAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/GetParamGen", ReplyAction="http://tempuri.org/ISedesolService/GetParamGenResponse")]
        SEDESOL.DataEntities.IntegrationObjects.GencodeDayParam GetParamGen();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/GetParamGen", ReplyAction="http://tempuri.org/ISedesolService/GetParamGenResponse")]
        System.Threading.Tasks.Task<SEDESOL.DataEntities.IntegrationObjects.GencodeDayParam> GetParamGenAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/GetApprovalByCaptureId", ReplyAction="http://tempuri.org/ISedesolService/GetApprovalByCaptureIdResponse")]
        System.Collections.Generic.List<SEDESOL.DataEntities.DTO.CaptureApprovalDTO> GetApprovalByCaptureId(int captureId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/GetApprovalByCaptureId", ReplyAction="http://tempuri.org/ISedesolService/GetApprovalByCaptureIdResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SEDESOL.DataEntities.DTO.CaptureApprovalDTO>> GetApprovalByCaptureIdAsync(int captureId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/GetProductAll", ReplyAction="http://tempuri.org/ISedesolService/GetProductAllResponse")]
        System.Collections.Generic.List<SEDESOL.DataEntities.DTO.ProductDTO> GetProductAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/GetProductAll", ReplyAction="http://tempuri.org/ISedesolService/GetProductAllResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SEDESOL.DataEntities.DTO.ProductDTO>> GetProductAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/GetProductById", ReplyAction="http://tempuri.org/ISedesolService/GetProductByIdResponse")]
        SEDESOL.DataEntities.DTO.ProductDTO GetProductById(int idProduct);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/GetProductById", ReplyAction="http://tempuri.org/ISedesolService/GetProductByIdResponse")]
        System.Threading.Tasks.Task<SEDESOL.DataEntities.DTO.ProductDTO> GetProductByIdAsync(int idProduct);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/SaveProduct", ReplyAction="http://tempuri.org/ISedesolService/SaveProductResponse")]
        SEDESOL.DataEntities.DTO.ProductDTO SaveProduct(SEDESOL.DataEntities.DTO.ProductDTO prodDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/SaveProduct", ReplyAction="http://tempuri.org/ISedesolService/SaveProductResponse")]
        System.Threading.Tasks.Task<SEDESOL.DataEntities.DTO.ProductDTO> SaveProductAsync(SEDESOL.DataEntities.DTO.ProductDTO prodDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/GetRationSearch", ReplyAction="http://tempuri.org/ISedesolService/GetRationSearchResponse")]
        SEDESOL.DataEntities.IntegrationObjects.RationModel GetRationSearch(int pYear, int pMonth);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/GetRationSearch", ReplyAction="http://tempuri.org/ISedesolService/GetRationSearchResponse")]
        System.Threading.Tasks.Task<SEDESOL.DataEntities.IntegrationObjects.RationModel> GetRationSearchAsync(int pYear, int pMonth);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/SaveRations", ReplyAction="http://tempuri.org/ISedesolService/SaveRationsResponse")]
        string SaveRations(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/SaveRations", ReplyAction="http://tempuri.org/ISedesolService/SaveRationsResponse")]
        System.Threading.Tasks.Task<string> SaveRationsAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/GetCouponData", ReplyAction="http://tempuri.org/ISedesolService/GetCouponDataResponse")]
        SEDESOL.DataEntities.IntegrationObjects.CouponModel GetCouponData(int pIdRation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/GetCouponData", ReplyAction="http://tempuri.org/ISedesolService/GetCouponDataResponse")]
        System.Threading.Tasks.Task<SEDESOL.DataEntities.IntegrationObjects.CouponModel> GetCouponDataAsync(int pIdRation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/GetCouponDataByState", ReplyAction="http://tempuri.org/ISedesolService/GetCouponDataByStateResponse")]
        System.Collections.Generic.List<SEDESOL.DataEntities.IntegrationObjects.CouponModel> GetCouponDataByState(int pIdState, int pIdYear, int pIdMonth);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/GetCouponDataByState", ReplyAction="http://tempuri.org/ISedesolService/GetCouponDataByStateResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SEDESOL.DataEntities.IntegrationObjects.CouponModel>> GetCouponDataByStateAsync(int pIdState, int pIdYear, int pIdMonth);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/GetDataExcel", ReplyAction="http://tempuri.org/ISedesolService/GetDataExcelResponse")]
        string GetDataExcel(int pIdState, int pIdMonth, int pIdYear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/GetDataExcel", ReplyAction="http://tempuri.org/ISedesolService/GetDataExcelResponse")]
        System.Threading.Tasks.Task<string> GetDataExcelAsync(int pIdState, int pIdMonth, int pIdYear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/GetConfiguration", ReplyAction="http://tempuri.org/ISedesolService/GetConfigurationResponse")]
        System.Collections.Generic.List<SEDESOL.DataEntities.DTO.ConfigurationDTO> GetConfiguration(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISedesolService/GetConfiguration", ReplyAction="http://tempuri.org/ISedesolService/GetConfigurationResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SEDESOL.DataEntities.DTO.ConfigurationDTO>> GetConfigurationAsync(string value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISedesolServiceChannel : SEDESOL.UI.SedesolService.ISedesolService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SedesolServiceClient : System.ServiceModel.ClientBase<SEDESOL.UI.SedesolService.ISedesolService>, SEDESOL.UI.SedesolService.ISedesolService {
        
        public SedesolServiceClient() {
        }
        
        public SedesolServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SedesolServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SedesolServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SedesolServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<SEDESOL.DataEntities.DTO.CaptureDTO> GetCaptures() {
            return base.Channel.GetCaptures();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SEDESOL.DataEntities.DTO.CaptureDTO>> GetCapturesAsync() {
            return base.Channel.GetCapturesAsync();
        }
        
        public System.Collections.Generic.List<SEDESOL.DataEntities.DTO.CaptureDTO> GetCapturesSearch(int userTypeId, int userId, int pState, int pSoupK, int pStatus) {
            return base.Channel.GetCapturesSearch(userTypeId, userId, pState, pSoupK, pStatus);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SEDESOL.DataEntities.DTO.CaptureDTO>> GetCapturesSearchAsync(int userTypeId, int userId, int pState, int pSoupK, int pStatus) {
            return base.Channel.GetCapturesSearchAsync(userTypeId, userId, pState, pSoupK, pStatus);
        }
        
        public System.Collections.Generic.List<SEDESOL.DataEntities.DTO.CaptureDTO> GetCapturesFilter(int userTypeId, int userId) {
            return base.Channel.GetCapturesFilter(userTypeId, userId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SEDESOL.DataEntities.DTO.CaptureDTO>> GetCapturesFilterAsync(int userTypeId, int userId) {
            return base.Channel.GetCapturesFilterAsync(userTypeId, userId);
        }
        
        public void ActivateCapture(int id) {
            base.Channel.ActivateCapture(id);
        }
        
        public System.Threading.Tasks.Task ActivateCaptureAsync(int id) {
            return base.Channel.ActivateCaptureAsync(id);
        }
        
        public void DeactivateCapture(int id) {
            base.Channel.DeactivateCapture(id);
        }
        
        public System.Threading.Tasks.Task DeactivateCaptureAsync(int id) {
            return base.Channel.DeactivateCaptureAsync(id);
        }
        
        public SEDESOL.DataEntities.DTO.CaptureDTO SaveCapture(SEDESOL.DataEntities.DTO.CaptureDTO capture) {
            return base.Channel.SaveCapture(capture);
        }
        
        public System.Threading.Tasks.Task<SEDESOL.DataEntities.DTO.CaptureDTO> SaveCaptureAsync(SEDESOL.DataEntities.DTO.CaptureDTO capture) {
            return base.Channel.SaveCaptureAsync(capture);
        }
        
        public bool UpdateCapture(SEDESOL.DataEntities.DTO.CaptureDTO capture) {
            return base.Channel.UpdateCapture(capture);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateCaptureAsync(SEDESOL.DataEntities.DTO.CaptureDTO capture) {
            return base.Channel.UpdateCaptureAsync(capture);
        }
        
        public SEDESOL.DataEntities.DTO.CaptureDTO GetCaptureById(int id) {
            return base.Channel.GetCaptureById(id);
        }
        
        public System.Threading.Tasks.Task<SEDESOL.DataEntities.DTO.CaptureDTO> GetCaptureByIdAsync(int id) {
            return base.Channel.GetCaptureByIdAsync(id);
        }
        
        public int SaveCaptureImage(SEDESOL.DataEntities.DTO.CaptureImageDTO dto) {
            return base.Channel.SaveCaptureImage(dto);
        }
        
        public System.Threading.Tasks.Task<int> SaveCaptureImageAsync(SEDESOL.DataEntities.DTO.CaptureImageDTO dto) {
            return base.Channel.SaveCaptureImageAsync(dto);
        }
        
        public string DeleteCaptureImage(int FileId) {
            return base.Channel.DeleteCaptureImage(FileId);
        }
        
        public System.Threading.Tasks.Task<string> DeleteCaptureImageAsync(int FileId) {
            return base.Channel.DeleteCaptureImageAsync(FileId);
        }
        
        public System.Collections.Generic.List<SEDESOL.DataEntities.DTO.CaptureImageDTO> GetImageByCaptureId(int pCaptureId) {
            return base.Channel.GetImageByCaptureId(pCaptureId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SEDESOL.DataEntities.DTO.CaptureImageDTO>> GetImageByCaptureIdAsync(int pCaptureId) {
            return base.Channel.GetImageByCaptureIdAsync(pCaptureId);
        }
        
        public System.Collections.Generic.List<SEDESOL.DataEntities.DTO.InspectionCodeDTO> GetCodesByUserId(int pUserId) {
            return base.Channel.GetCodesByUserId(pUserId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SEDESOL.DataEntities.DTO.InspectionCodeDTO>> GetCodesByUserIdAsync(int pUserId) {
            return base.Channel.GetCodesByUserIdAsync(pUserId);
        }
        
        public string SendToApproval(SEDESOL.DataEntities.DTO.CaptureApprovalDTO dto) {
            return base.Channel.SendToApproval(dto);
        }
        
        public System.Threading.Tasks.Task<string> SendToApprovalAsync(SEDESOL.DataEntities.DTO.CaptureApprovalDTO dto) {
            return base.Channel.SendToApprovalAsync(dto);
        }
        
        public SEDESOL.DataEntities.IntegrationObjects.CaptureParam GetParamCapture(int userTypeId, int userId) {
            return base.Channel.GetParamCapture(userTypeId, userId);
        }
        
        public System.Threading.Tasks.Task<SEDESOL.DataEntities.IntegrationObjects.CaptureParam> GetParamCaptureAsync(int userTypeId, int userId) {
            return base.Channel.GetParamCaptureAsync(userTypeId, userId);
        }
        
        public string EditStatus(int idStatus, int idCapture, int idUserType) {
            return base.Channel.EditStatus(idStatus, idCapture, idUserType);
        }
        
        public System.Threading.Tasks.Task<string> EditStatusAsync(int idStatus, int idCapture, int idUserType) {
            return base.Channel.EditStatusAsync(idStatus, idCapture, idUserType);
        }
        
        public System.Collections.Generic.List<SEDESOL.DataEntities.DTO.StateDTO> GetStates() {
            return base.Channel.GetStates();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SEDESOL.DataEntities.DTO.StateDTO>> GetStatesAsync() {
            return base.Channel.GetStatesAsync();
        }
        
        public System.Collections.Generic.List<SEDESOL.DataEntities.DTO.StateDTO> GetStatesFilter(int userTypeId, int userId) {
            return base.Channel.GetStatesFilter(userTypeId, userId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SEDESOL.DataEntities.DTO.StateDTO>> GetStatesFilterAsync(int userTypeId, int userId) {
            return base.Channel.GetStatesFilterAsync(userTypeId, userId);
        }
        
        public System.Collections.Generic.List<SEDESOL.DataEntities.DTO.StatusDTO> GetStatus() {
            return base.Channel.GetStatus();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SEDESOL.DataEntities.DTO.StatusDTO>> GetStatusAsync() {
            return base.Channel.GetStatusAsync();
        }
        
        public System.Collections.Generic.List<SEDESOL.DataEntities.DTO.YearDTO> GetYears() {
            return base.Channel.GetYears();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SEDESOL.DataEntities.DTO.YearDTO>> GetYearsAsync() {
            return base.Channel.GetYearsAsync();
        }
        
        public System.Collections.Generic.List<SEDESOL.DataEntities.DTO.MonthDTO> GetMonths() {
            return base.Channel.GetMonths();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SEDESOL.DataEntities.DTO.MonthDTO>> GetMonthsAsync() {
            return base.Channel.GetMonthsAsync();
        }
        
        public void UpdateState(SEDESOL.DataEntities.DTO.StateDTO dto) {
            base.Channel.UpdateState(dto);
        }
        
        public System.Threading.Tasks.Task UpdateStateAsync(SEDESOL.DataEntities.DTO.StateDTO dto) {
            return base.Channel.UpdateStateAsync(dto);
        }
        
        public void UpdateStatus(SEDESOL.DataEntities.DTO.StatusDTO dto) {
            base.Channel.UpdateStatus(dto);
        }
        
        public System.Threading.Tasks.Task UpdateStatusAsync(SEDESOL.DataEntities.DTO.StatusDTO dto) {
            return base.Channel.UpdateStatusAsync(dto);
        }
        
        public void UpdateYear(SEDESOL.DataEntities.DTO.YearDTO dto) {
            base.Channel.UpdateYear(dto);
        }
        
        public System.Threading.Tasks.Task UpdateYearAsync(SEDESOL.DataEntities.DTO.YearDTO dto) {
            return base.Channel.UpdateYearAsync(dto);
        }
        
        public void UpdateMonth(SEDESOL.DataEntities.DTO.MonthDTO dto) {
            base.Channel.UpdateMonth(dto);
        }
        
        public System.Threading.Tasks.Task UpdateMonthAsync(SEDESOL.DataEntities.DTO.MonthDTO dto) {
            return base.Channel.UpdateMonthAsync(dto);
        }
        
        public void ActivateStatus(int id) {
            base.Channel.ActivateStatus(id);
        }
        
        public System.Threading.Tasks.Task ActivateStatusAsync(int id) {
            return base.Channel.ActivateStatusAsync(id);
        }
        
        public void DeactivateStatus(int id) {
            base.Channel.DeactivateStatus(id);
        }
        
        public System.Threading.Tasks.Task DeactivateStatusAsync(int id) {
            return base.Channel.DeactivateStatusAsync(id);
        }
        
        public void ActivateState(int id) {
            base.Channel.ActivateState(id);
        }
        
        public System.Threading.Tasks.Task ActivateStateAsync(int id) {
            return base.Channel.ActivateStateAsync(id);
        }
        
        public void DeactivateState(int id) {
            base.Channel.DeactivateState(id);
        }
        
        public System.Threading.Tasks.Task DeactivateStateAsync(int id) {
            return base.Channel.DeactivateStateAsync(id);
        }
        
        public void ActivateYear(int id) {
            base.Channel.ActivateYear(id);
        }
        
        public System.Threading.Tasks.Task ActivateYearAsync(int id) {
            return base.Channel.ActivateYearAsync(id);
        }
        
        public void DeactivateYear(int id) {
            base.Channel.DeactivateYear(id);
        }
        
        public System.Threading.Tasks.Task DeactivateYearAsync(int id) {
            return base.Channel.DeactivateYearAsync(id);
        }
        
        public void ActivateMonth(int id) {
            base.Channel.ActivateMonth(id);
        }
        
        public System.Threading.Tasks.Task ActivateMonthAsync(int id) {
            return base.Channel.ActivateMonthAsync(id);
        }
        
        public void DeactivateMonth(int id) {
            base.Channel.DeactivateMonth(id);
        }
        
        public System.Threading.Tasks.Task DeactivateMonthAsync(int id) {
            return base.Channel.DeactivateMonthAsync(id);
        }
        
        public SEDESOL.DataEntities.IntegrationObjects.CodeParam GetParamCode(int pUserId) {
            return base.Channel.GetParamCode(pUserId);
        }
        
        public System.Threading.Tasks.Task<SEDESOL.DataEntities.IntegrationObjects.CodeParam> GetParamCodeAsync(int pUserId) {
            return base.Channel.GetParamCodeAsync(pUserId);
        }
        
        public string GenerateCode(int pUserId) {
            return base.Channel.GenerateCode(pUserId);
        }
        
        public System.Threading.Tasks.Task<string> GenerateCodeAsync(int pUserId) {
            return base.Channel.GenerateCodeAsync(pUserId);
        }
        
        public System.Collections.Generic.List<SEDESOL.DataEntities.DTO.StateDTO> GetActiveStates() {
            return base.Channel.GetActiveStates();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SEDESOL.DataEntities.DTO.StateDTO>> GetActiveStatesAsync() {
            return base.Channel.GetActiveStatesAsync();
        }
        
        public System.Collections.Generic.List<SEDESOL.DataEntities.DTO.ConditionDTO> GetActiveCondition() {
            return base.Channel.GetActiveCondition();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SEDESOL.DataEntities.DTO.ConditionDTO>> GetActiveConditionAsync() {
            return base.Channel.GetActiveConditionAsync();
        }
        
        public System.Collections.Generic.List<SEDESOL.DataEntities.DTO.RegionDTO> GetActiveRegions() {
            return base.Channel.GetActiveRegions();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SEDESOL.DataEntities.DTO.RegionDTO>> GetActiveRegionsAsync() {
            return base.Channel.GetActiveRegionsAsync();
        }
        
        public SEDESOL.DataEntities.DTO.AttendanceDTO SaveAttendance(SEDESOL.DataEntities.DTO.AttendanceDTO dto) {
            return base.Channel.SaveAttendance(dto);
        }
        
        public System.Threading.Tasks.Task<SEDESOL.DataEntities.DTO.AttendanceDTO> SaveAttendanceAsync(SEDESOL.DataEntities.DTO.AttendanceDTO dto) {
            return base.Channel.SaveAttendanceAsync(dto);
        }
        
        public SEDESOL.DataEntities.DTO.AttendanceDTO GetAttendanceById(int id) {
            return base.Channel.GetAttendanceById(id);
        }
        
        public System.Threading.Tasks.Task<SEDESOL.DataEntities.DTO.AttendanceDTO> GetAttendanceByIdAsync(int id) {
            return base.Channel.GetAttendanceByIdAsync(id);
        }
        
        public string DeleteAttendance(int id) {
            return base.Channel.DeleteAttendance(id);
        }
        
        public System.Threading.Tasks.Task<string> DeleteAttendanceAsync(int id) {
            return base.Channel.DeleteAttendanceAsync(id);
        }
        
        public System.Collections.Generic.List<SEDESOL.DataEntities.DTO.AttendanceDTO> GetDataForAc(string term) {
            return base.Channel.GetDataForAc(term);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SEDESOL.DataEntities.DTO.AttendanceDTO>> GetDataForAcAsync(string term) {
            return base.Channel.GetDataForAcAsync(term);
        }
        
        public string GetAttendanceReport(int pCaptureId) {
            return base.Channel.GetAttendanceReport(pCaptureId);
        }
        
        public System.Threading.Tasks.Task<string> GetAttendanceReportAsync(int pCaptureId) {
            return base.Channel.GetAttendanceReportAsync(pCaptureId);
        }
        
        public string GetCaptureReport(System.Collections.Generic.List<SEDESOL.DataEntities.DTO.FilterDTO> filters) {
            return base.Channel.GetCaptureReport(filters);
        }
        
        public System.Threading.Tasks.Task<string> GetCaptureReportAsync(System.Collections.Generic.List<SEDESOL.DataEntities.DTO.FilterDTO> filters) {
            return base.Channel.GetCaptureReportAsync(filters);
        }
        
        public System.Collections.Generic.List<SEDESOL.DataEntities.DTO.SoupKitchenDTO> GetSoupKitchenByUser(int userTypeId, int userId) {
            return base.Channel.GetSoupKitchenByUser(userTypeId, userId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SEDESOL.DataEntities.DTO.SoupKitchenDTO>> GetSoupKitchenByUserAsync(int userTypeId, int userId) {
            return base.Channel.GetSoupKitchenByUserAsync(userTypeId, userId);
        }
        
        public SEDESOL.DataEntities.DTO.UserDTO ValidateUser(SEDESOL.DataEntities.IntegrationObjects.UserValidationRequest req) {
            return base.Channel.ValidateUser(req);
        }
        
        public System.Threading.Tasks.Task<SEDESOL.DataEntities.DTO.UserDTO> ValidateUserAsync(SEDESOL.DataEntities.IntegrationObjects.UserValidationRequest req) {
            return base.Channel.ValidateUserAsync(req);
        }
        
        public SEDESOL.DataEntities.DTO.SoupKitchenDTO SaveSoupKitchen(SEDESOL.DataEntities.DTO.SoupKitchenDTO dto) {
            return base.Channel.SaveSoupKitchen(dto);
        }
        
        public System.Threading.Tasks.Task<SEDESOL.DataEntities.DTO.SoupKitchenDTO> SaveSoupKitchenAsync(SEDESOL.DataEntities.DTO.SoupKitchenDTO dto) {
            return base.Channel.SaveSoupKitchenAsync(dto);
        }
        
        public System.Collections.Generic.List<SEDESOL.DataEntities.DTO.SoupKitchenDTO> GetSoupKitchenAll() {
            return base.Channel.GetSoupKitchenAll();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SEDESOL.DataEntities.DTO.SoupKitchenDTO>> GetSoupKitchenAllAsync() {
            return base.Channel.GetSoupKitchenAllAsync();
        }
        
        public System.Collections.Generic.List<SEDESOL.DataEntities.DTO.SoupKitchenDTO> GetSoupKitchenToAssignUser(int id) {
            return base.Channel.GetSoupKitchenToAssignUser(id);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SEDESOL.DataEntities.DTO.SoupKitchenDTO>> GetSoupKitchenToAssignUserAsync(int id) {
            return base.Channel.GetSoupKitchenToAssignUserAsync(id);
        }
        
        public System.Collections.Generic.List<SEDESOL.DataEntities.DTO.SoupKitchenDTO> GetSKAssignedUser(int id) {
            return base.Channel.GetSKAssignedUser(id);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SEDESOL.DataEntities.DTO.SoupKitchenDTO>> GetSKAssignedUserAsync(int id) {
            return base.Channel.GetSKAssignedUserAsync(id);
        }
        
        public SEDESOL.DataEntities.DTO.SoupKitchenDTO GetSoupKitchenById(int id) {
            return base.Channel.GetSoupKitchenById(id);
        }
        
        public System.Threading.Tasks.Task<SEDESOL.DataEntities.DTO.SoupKitchenDTO> GetSoupKitchenByIdAsync(int id) {
            return base.Channel.GetSoupKitchenByIdAsync(id);
        }
        
        public void Deactivate(int id) {
            base.Channel.Deactivate(id);
        }
        
        public System.Threading.Tasks.Task DeactivateAsync(int id) {
            return base.Channel.DeactivateAsync(id);
        }
        
        public void Activate(int id) {
            base.Channel.Activate(id);
        }
        
        public System.Threading.Tasks.Task ActivateAsync(int id) {
            return base.Channel.ActivateAsync(id);
        }
        
        public System.Collections.Generic.List<SEDESOL.DataEntities.DTO.SkUserTypeDTOcs> GetUserTypeBySKId(int skId) {
            return base.Channel.GetUserTypeBySKId(skId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SEDESOL.DataEntities.DTO.SkUserTypeDTOcs>> GetUserTypeBySKIdAsync(int skId) {
            return base.Channel.GetUserTypeBySKIdAsync(skId);
        }
        
        public string DeleteUserTypeSk(int id) {
            return base.Channel.DeleteUserTypeSk(id);
        }
        
        public System.Threading.Tasks.Task<string> DeleteUserTypeSkAsync(int id) {
            return base.Channel.DeleteUserTypeSkAsync(id);
        }
        
        public SEDESOL.DataEntities.DTO.UserDTO SaveUser(SEDESOL.DataEntities.DTO.UserDTO dto) {
            return base.Channel.SaveUser(dto);
        }
        
        public System.Threading.Tasks.Task<SEDESOL.DataEntities.DTO.UserDTO> SaveUserAsync(SEDESOL.DataEntities.DTO.UserDTO dto) {
            return base.Channel.SaveUserAsync(dto);
        }
        
        public System.Collections.Generic.List<SEDESOL.DataEntities.DTO.UserDTO> GetUserAll() {
            return base.Channel.GetUserAll();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SEDESOL.DataEntities.DTO.UserDTO>> GetUserAllAsync() {
            return base.Channel.GetUserAllAsync();
        }
        
        public SEDESOL.DataEntities.DTO.UserDTO GetUserById(int id) {
            return base.Channel.GetUserById(id);
        }
        
        public System.Threading.Tasks.Task<SEDESOL.DataEntities.DTO.UserDTO> GetUserByIdAsync(int id) {
            return base.Channel.GetUserByIdAsync(id);
        }
        
        public void DeactivateUser(int id) {
            base.Channel.DeactivateUser(id);
        }
        
        public System.Threading.Tasks.Task DeactivateUserAsync(int id) {
            return base.Channel.DeactivateUserAsync(id);
        }
        
        public void ActivateUser(int id) {
            base.Channel.ActivateUser(id);
        }
        
        public System.Threading.Tasks.Task ActivateUserAsync(int id) {
            return base.Channel.ActivateUserAsync(id);
        }
        
        public System.Collections.Generic.List<SEDESOL.DataEntities.DTO.UserTypeDTO> GetUserTypeAll() {
            return base.Channel.GetUserTypeAll();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SEDESOL.DataEntities.DTO.UserTypeDTO>> GetUserTypeAllAsync() {
            return base.Channel.GetUserTypeAllAsync();
        }
        
        public System.Collections.Generic.List<SEDESOL.DataEntities.DTO.UserTypeDTO> GetUserTypeApproval() {
            return base.Channel.GetUserTypeApproval();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SEDESOL.DataEntities.DTO.UserTypeDTO>> GetUserTypeApprovalAsync() {
            return base.Channel.GetUserTypeApprovalAsync();
        }
        
        public SEDESOL.DataEntities.DTO.SkUserTypeDTOcs SaveUserTypeSK(SEDESOL.DataEntities.DTO.SkUserTypeDTOcs dto) {
            return base.Channel.SaveUserTypeSK(dto);
        }
        
        public System.Threading.Tasks.Task<SEDESOL.DataEntities.DTO.SkUserTypeDTOcs> SaveUserTypeSKAsync(SEDESOL.DataEntities.DTO.SkUserTypeDTOcs dto) {
            return base.Channel.SaveUserTypeSKAsync(dto);
        }
        
        public SEDESOL.DataEntities.DTO.UserSoupKitchen SaveUserSoupKitchen(SEDESOL.DataEntities.DTO.UserSoupKitchen dto) {
            return base.Channel.SaveUserSoupKitchen(dto);
        }
        
        public System.Threading.Tasks.Task<SEDESOL.DataEntities.DTO.UserSoupKitchen> SaveUserSoupKitchenAsync(SEDESOL.DataEntities.DTO.UserSoupKitchen dto) {
            return base.Channel.SaveUserSoupKitchenAsync(dto);
        }
        
        public string DeleteUserSoupKitchen(int idSk, int idUser) {
            return base.Channel.DeleteUserSoupKitchen(idSk, idUser);
        }
        
        public System.Threading.Tasks.Task<string> DeleteUserSoupKitchenAsync(int idSk, int idUser) {
            return base.Channel.DeleteUserSoupKitchenAsync(idSk, idUser);
        }
        
        public SEDESOL.DataEntities.DTO.InspectionCodeDTO SaveInspectionCode(SEDESOL.DataEntities.DTO.InspectionCodeDTO dto) {
            return base.Channel.SaveInspectionCode(dto);
        }
        
        public System.Threading.Tasks.Task<SEDESOL.DataEntities.DTO.InspectionCodeDTO> SaveInspectionCodeAsync(SEDESOL.DataEntities.DTO.InspectionCodeDTO dto) {
            return base.Channel.SaveInspectionCodeAsync(dto);
        }
        
        public System.Collections.Generic.List<SEDESOL.DataEntities.DTO.GencodeDayDTO> GetGenerationCodeDayAll() {
            return base.Channel.GetGenerationCodeDayAll();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SEDESOL.DataEntities.DTO.GencodeDayDTO>> GetGenerationCodeDayAllAsync() {
            return base.Channel.GetGenerationCodeDayAllAsync();
        }
        
        public SEDESOL.DataEntities.DTO.GencodeDayDTO SaveGencodeDay(SEDESOL.DataEntities.DTO.GencodeDayDTO dto) {
            return base.Channel.SaveGencodeDay(dto);
        }
        
        public System.Threading.Tasks.Task<SEDESOL.DataEntities.DTO.GencodeDayDTO> SaveGencodeDayAsync(SEDESOL.DataEntities.DTO.GencodeDayDTO dto) {
            return base.Channel.SaveGencodeDayAsync(dto);
        }
        
        public SEDESOL.DataEntities.DTO.GencodeDayDTO GetGenerationCodeDayById(int Id) {
            return base.Channel.GetGenerationCodeDayById(Id);
        }
        
        public System.Threading.Tasks.Task<SEDESOL.DataEntities.DTO.GencodeDayDTO> GetGenerationCodeDayByIdAsync(int Id) {
            return base.Channel.GetGenerationCodeDayByIdAsync(Id);
        }
        
        public SEDESOL.DataEntities.IntegrationObjects.GencodeDayParam GetParamGen() {
            return base.Channel.GetParamGen();
        }
        
        public System.Threading.Tasks.Task<SEDESOL.DataEntities.IntegrationObjects.GencodeDayParam> GetParamGenAsync() {
            return base.Channel.GetParamGenAsync();
        }
        
        public System.Collections.Generic.List<SEDESOL.DataEntities.DTO.CaptureApprovalDTO> GetApprovalByCaptureId(int captureId) {
            return base.Channel.GetApprovalByCaptureId(captureId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SEDESOL.DataEntities.DTO.CaptureApprovalDTO>> GetApprovalByCaptureIdAsync(int captureId) {
            return base.Channel.GetApprovalByCaptureIdAsync(captureId);
        }
        
        public System.Collections.Generic.List<SEDESOL.DataEntities.DTO.ProductDTO> GetProductAll() {
            return base.Channel.GetProductAll();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SEDESOL.DataEntities.DTO.ProductDTO>> GetProductAllAsync() {
            return base.Channel.GetProductAllAsync();
        }
        
        public SEDESOL.DataEntities.DTO.ProductDTO GetProductById(int idProduct) {
            return base.Channel.GetProductById(idProduct);
        }
        
        public System.Threading.Tasks.Task<SEDESOL.DataEntities.DTO.ProductDTO> GetProductByIdAsync(int idProduct) {
            return base.Channel.GetProductByIdAsync(idProduct);
        }
        
        public SEDESOL.DataEntities.DTO.ProductDTO SaveProduct(SEDESOL.DataEntities.DTO.ProductDTO prodDto) {
            return base.Channel.SaveProduct(prodDto);
        }
        
        public System.Threading.Tasks.Task<SEDESOL.DataEntities.DTO.ProductDTO> SaveProductAsync(SEDESOL.DataEntities.DTO.ProductDTO prodDto) {
            return base.Channel.SaveProductAsync(prodDto);
        }
        
        public SEDESOL.DataEntities.IntegrationObjects.RationModel GetRationSearch(int pYear, int pMonth) {
            return base.Channel.GetRationSearch(pYear, pMonth);
        }
        
        public System.Threading.Tasks.Task<SEDESOL.DataEntities.IntegrationObjects.RationModel> GetRationSearchAsync(int pYear, int pMonth) {
            return base.Channel.GetRationSearchAsync(pYear, pMonth);
        }
        
        public string SaveRations(string data) {
            return base.Channel.SaveRations(data);
        }
        
        public System.Threading.Tasks.Task<string> SaveRationsAsync(string data) {
            return base.Channel.SaveRationsAsync(data);
        }
        
        public SEDESOL.DataEntities.IntegrationObjects.CouponModel GetCouponData(int pIdRation) {
            return base.Channel.GetCouponData(pIdRation);
        }
        
        public System.Threading.Tasks.Task<SEDESOL.DataEntities.IntegrationObjects.CouponModel> GetCouponDataAsync(int pIdRation) {
            return base.Channel.GetCouponDataAsync(pIdRation);
        }
        
        public System.Collections.Generic.List<SEDESOL.DataEntities.IntegrationObjects.CouponModel> GetCouponDataByState(int pIdState, int pIdYear, int pIdMonth) {
            return base.Channel.GetCouponDataByState(pIdState, pIdYear, pIdMonth);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SEDESOL.DataEntities.IntegrationObjects.CouponModel>> GetCouponDataByStateAsync(int pIdState, int pIdYear, int pIdMonth) {
            return base.Channel.GetCouponDataByStateAsync(pIdState, pIdYear, pIdMonth);
        }
        
        public string GetDataExcel(int pIdState, int pIdMonth, int pIdYear) {
            return base.Channel.GetDataExcel(pIdState, pIdMonth, pIdYear);
        }
        
        public System.Threading.Tasks.Task<string> GetDataExcelAsync(int pIdState, int pIdMonth, int pIdYear) {
            return base.Channel.GetDataExcelAsync(pIdState, pIdMonth, pIdYear);
        }
        
        public System.Collections.Generic.List<SEDESOL.DataEntities.DTO.ConfigurationDTO> GetConfiguration(string value) {
            return base.Channel.GetConfiguration(value);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SEDESOL.DataEntities.DTO.ConfigurationDTO>> GetConfigurationAsync(string value) {
            return base.Channel.GetConfigurationAsync(value);
        }
    }
}
